@baseUrl = http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODg4ZTcxZWNkM2JlMDVlNzhkNzdiMzIiLCJpYXQiOjE3NTc5MzIyMzYsImV4cCI6MTc1OTIyODIzNn0.hs730Muycj3vRVkxNZWLaL7Xp2kI--b8DpY02rfPaTc
@userToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlwSWQiOiI2OGJhODk0M2ZhNjFhYzRjYjYyYTg1NjIiLCJpYXQiOjE3NTgxMDMyMDksImV4cCI6MTc1ODEwNjgwOX0.kSuWUrwbTM_tyfFxUPaZyHMTTkdJuNKT6zTpyyzDeK4

### Create a package list
POST {{baseUrl}}/package-lists/688f747bc6ba776409c94468
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name":"Muffler"
}

###get all pacakage lists
GET {{baseUrl}}/package-lists/688f747bc6ba776409c94468
Authorization: Bearer {{token}}

### get a  pacakage list by id
GET {{baseUrl}}/package-lists/688f747bc6ba776409c94468/6890d006868cb031d32f5b87
Authorization: Bearer {{token}}


### Update a package list
PATCH {{baseUrl}}/package-lists/688f747bc6ba776409c94468/6890d006868cb031d32f5b87
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "completed": true
}

### Delete a package list
DELETE {{baseUrl}}/package-lists/688f747bc6ba776409c94468/6890d006868cb031d32f5b87








### Create a user
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name":"ramesh khatri",
  "email":"ramesh45@gmail.com",
  "password":"ramesh@123"
}


### Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

###Get a user list by id
GET {{baseUrl}}/users/6889d96227cda762dab88fd3
Content-Type: application/json
Authorization: Bearer {{token}}


###Update the user
PATCH {{baseUrl}}/users/687f3698ac13ba152caef7a4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name":"Durga Katwal",
  "email":"dkatwal254@gmail.com",
  "password":"durga@123"
}


###delete the user by id
DELETE {{baseUrl}}/users/688617567a3f61b41f5e80f6
Authorization: Bearer {{token}}



### register user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name":"Abhishek Katwal",
  "email":"dkatwal441@gmail.com",
  "password":"abhishek@123"
}

###login user
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "dkatwal253@gmail.com",
  "password": "durga@123"
}

###get the user profile
GET {{baseUrl}}/users/profile
Content-Type: application/json
Authorization: Bearer {{token}}

###Update User Profile (bio and preferences)
PATCH {{baseUrl}}/users/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bio": "Nature lover and travel enthusiast",
  "preferences": ["hiking", "mountains", "food"]
}

###post the avatar
POST {{baseUrl}}/users/profile/avatar
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "avatar": "https://png.pngtree.com/png-clipart/20230927/original/pngtree-man-avatar-image-for-profile-png-image_13001882.png"
}

### Create a new trip
POST {{baseUrl}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Pokhara Manang Mustang Tour",
  "description": "Good to travel",
  "startDate": "2025-08-15",
  "endDate": "2025-08-30",
  "destination": ["Pokhara", "Jomsom", "Muktinath", "Manakamana"],
  "budget": {
    "total": 50000,
    "spent": 0
  },
  "transport": {
    "mode": "Bus",
    "details": "Deluxe Tourist Bus"
  },
  "accommodation": {
    "name": "Hotel Lake Side",
    "address": "Lakeside, Pokhara",
    "checkIn": "2025-08-01",
    "checkOut": "2025-08-15"
  },
  "notes": "Excited for the trip!",
  "status": "Ongoing"
}



### Add an expense to a trip
POST {{baseUrl}}/trips/688f747bc6ba776409c94468/expenses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date": "2025-08-11",
  "amount": 1200,
  "name": "Taxi Fare"
}

###Get all the trips
GET {{baseUrl}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}


###Get the trip by id
GET {{baseUrl}}/trips/689b6c3a9e9c10549ba974ea
Content-Type: application/json
Authorization: Bearer {{token}}

###update trip
PATCH {{baseUrl}}/trips/6889d96227cda762dab88fd2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "transport":{
    "mode":"Flight"
  }
}

###delete trip
DELETE {{baseUrl}}/trips/688f741d323a3eb1c49d9054
Content-Type: application/json
Authorization: Bearer {{token}}




### Create an itinerary
POST {{baseUrl}}/itinerary
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tripId": "688f747bc6ba776409c94468",
  "title": "Day 1",
  "description": "This is a description of the itinerary Day 1",
  "date": "2025-08-16",
  "activities": [
    {
      "name": "Check in at Hotel",
      "time": "08:00 AM",
      "notes": ["Check In", "Breakfast", "Rest"]
    },
    {
      "name": "Visit Lake Side",
      "time": "11:00 AM - 02:00 PM",
      "notes": ["Visit Lake Side", "Tal Barahi Temple", "Do Boating", "Click Pictures"]
    },
    {
      "name": "Visit Street 9",
      "time": "02:00 PM - 03:00 PM",
      "notes": ["Have Lunch", "Hire a Cab"]
    }
  ]
}

###Get all the itinerary 
GET {{baseUrl}}/itineraries/688f747bc6ba776409c94468
Content-Type: application/json
Authorization: Bearer {{token}}

###Get the itinerary by id 
GET {{baseUrl}}/itineraries/688f747bc6ba776409c94468/688f798846ba9c5d2ca6247c
Content-Type: application/json
Authorization: Bearer {{token}}

###Update the itinerary
PATCH {{baseUrl}}/itineraries/68ba8943fa61ac4cb62a8562/68c7dfc02b1c4283274a819b
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "activities": [
    {
      "name": "Check in at Hotel",
      "time": "08:00 AM",
      "notes": ["Check In", "Breakfast", "Rest"]
    },
    {
      "name": "Visit Lake Side",
      "time": "11:00 AM - 02:00 PM",
      "notes": ["Visit Lake Side", "Tal Barahi Temple", "Do Boating", "Click Pictures"]
    },
    {
      "name": "Visit Street 9",
      "time": "02:00 PM - 03:00 PM",
      "notes": ["Have Lunch", "Hire a Cab"]
    }
  ]
}


###delete itinerary
DELETE {{baseUrl}}/itineraries/688f747bc6ba776409c94468/688f798846ba9c5d2ca6247c
Content-Type: application/json
Authorization: Bearer {{token}}




###Invite collaborator to a trip with the trip id
POST {{baseUrl}}/trips/689b6c3a9e9c10549ba974ea/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email":["dkatwal441@gmail.com"]
}


###Accept the invitation to the trip
GET {{baseUrl}}/trips/689b6c3a9e9c10549ba974ea/invite/accept?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlwSWQiOiI2ODliNmMzYTllOWMxMDU0OWJhOTc0ZWEiLCJpYXQiOjE3NTUxMDU5OTYsImV4cCI6MTc1NTEwOTU5Nn0.hVlmkNdg2yNABXP3SfZM-b1LULsZcRdmzjDpC_XGyQo
Authorization: Bearer {{userToken}}

###Delete a file from a trip
DELETE {{baseUrl}}/trips/689b6c3a9e9c10549ba974ea/files?file=wander-wise/trips/Pokhara Manang Mustang Tour_689b6c3a9e9c10549ba974ea/07f7f625076e8b348c9e5290b5345979_rrlvk2
Authorization: Bearer {{token}}

###send the message 
POST {{baseUrl}}/689b6c3a9e9c10549ba974ea/messages
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text":"Hey this is the first message send through the socket.io"
}

###Reply to the msg
POST {{baseUrl}}/689b6c3a9e9c10549ba974ea/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODljY2E3MGE4ZDhhZDNjZjcyZGZiZDUiLCJpYXQiOjE3NTUyNzUyNDUsImV4cCI6MTc1NjU3MTI0NX0.WetV4UAuUVf82TeAFdO5VGaXY9EAyslgktQ2GZidn14

{
  "text":"Hello replying to the first msg ."
}

###get all the messages 
GET {{baseUrl}}/trips/689b6c3a9e9c10549ba974ea/messages
Content-Type: application/json
Authorization: Bearer {{token}}


###post the review for the trip using tripid
POST {{baseUrl}}/trips/689b6c3a9e9c10549ba974ea/reviews
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "rating":5,
  "comment":"Amazing trip! Had a wonderful experience."
}

###get all the reviews
GET {{baseUrl}}/trips/689b6c3a9e9c10549ba974ea/reviews
Content-Type: application/json
Authorization: Bearer {{token}}


###delete the review by review id
DELETE {{baseUrl}}/trips/689b6c3a9e9c10549ba974ea/reviews/68a05884bab4ba2904d20b5e
Content-Type: application/json
Authorization: Bearer {{token}}

